# Задание 1
Импортируйте библиотеку Numpy и дайте ей псевдоним np.

In [1]:
import numpy as np

    1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [18]:
a = np.arange(12, 24)

    2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [19]:
a1 = a.reshape(3,4)
a2 = a.reshape(4,3)
a3 = a.reshape(2,6)
a4 = a.reshape(6,2)
a5 = a.reshape(12,1)

    3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [20]:
a6 = a.reshape(2,-1)
a7 = a.reshape(3,-1)
a8 = a.reshape(4,-1)
a9 = a.reshape(-1,2)
a10 = a.reshape(-1,1)

    4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [21]:
#a10 - состоит из 1 столбца и 12 строк
if a10.ndim == 1:
    print("Можно")
else:
    print("Нельзя")

Нельзя


    5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения 
со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [22]:
rm = np.random.randn(3,4)
print(rm)
rm1 = rm.flatten()
print(f'Число измерений нового массива - {rm1.ndim}')
if rm.size == rm1.size:
    print(f'Аттрибут size совпадает и равен {rm.size}')


[[ 1.57921282  0.76743473 -0.46947439  0.54256004]
 [-0.46341769 -0.46572975  0.24196227 -1.91328024]
 [-1.72491783 -0.56228753 -1.01283112  0.31424733]]
Число измерений нового массива - 1
Аттрибут size совпадает и равен 12


    6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.
Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2.
В чем разница между массивами a и b?

In [23]:
a = np.arange(20, 0, -2)
b = np.arange(20, 1, -2).reshape(1,10)
print(f"Разница между массивами а и b состоит в том, что массив а - одномерный, а массив b - двумерный")
print(f"a.ndim = {a.ndim}\nb.ndim = {b.ndim}")

Разница между массивами а и b состоит в том, что массив а - одномерный, а массив b - двумерный
a.ndim = 1
b.ndim = 2


    7. Вертикально соединить массивы a и b. a - двумерный массив из нулей, 
число строк которого больше 1 и на 1 меньше, чем число строк двумерного 
массива b, состоящего из единиц.
Итоговый массив v должен иметь атрибут size, равный 10.

In [24]:
b = np.ones((3,2))
print(b)
a = np.zeros((2,2))
print(a)
v = np.vstack((a,b))
print(v)
print(v.size)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]]
[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
10


    8. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12.
Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 
4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A.
Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения.
Какой размер имеет матрица B?
Получится ли вычислить обратную матрицу для матрицы B и почему?

In [25]:
a = np.arange(12)
A = a.reshape(4,3)
print(A)
At = np.transpose(A)
print(At)
B = A.dot(At)
print(B)
print(f"Размер матрицы В = {B.shape}")
print(f"Матрицу, обратную B вычислить не получится, так как определитель В = {np.linalg.det(B)}")

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
Размер матрицы В = (4, 4)
Матрицу, обратную B вычислить не получится, так как определитель В = 0.0


    9. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42. 
Создайте одномерный массив c, составленный из последовательности 16-ти случайных целых чисел от 0 до 16 невключительно. 
Поменяйте его форму так, чтобы получилась квадратная матрица C.
Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10.
Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [26]:
np.random.seed(42)
c = np.random.randint(0,16,16)
C = c.reshape(4,4)
D = C * 10 + B
print(f"Определитель матрицы D = {np.linalg.det(D)}")
print(f"Ранг матрицы D = {np.linalg.matrix_rank(D)}")
D_inv = np.linalg.inv(D)
print(f"Матрица, обратная D = \n{D_inv}")

Определитель матрицы D = -28511999.999999944
Ранг матрицы D = 4
Матрица, обратная D = 
[[ 0.00935396  0.04486532  0.05897517 -0.07286055]
 [-0.01503577 -0.00122896 -0.00192971  0.00967873]
 [-0.00356692 -0.01782828 -0.04152146  0.04326178]
 [ 0.00909091 -0.00181818  0.01272727 -0.01090909]]


    10. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4. Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [64]:
D_inv[np.where(D_inv < 0)] = 0
D_inv[np.where(D_inv > 0)] = 1
print(np.unique(D_inv))
E = np.where(D_inv, B, C)
print(E)

[0. 1.]
[[  5  14  23  14]
 [ 10   7  12 122]
 [  6   9   2 212]
 [ 32  10 212   4]]


# Задание 2
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов.
Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7.
Будем считать, что каждый столбец - это признак, а строка - наблюдение.
Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy.
Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [70]:
a = np.array([[1, 2, 3, 3, 1], [6, 8, 11, 10, 7]])
a = a.transpose()
print(a)
mean_a = np.mean(a, axis = 0)
print(mean_a)

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]
[2.  8.4]


# Задание 3
Вычислите массив a_centered, отняв от значений массива а 
средние значения соответствующих признаков, содержащиеся в массиве mean_a.
Вычисление должно производиться в одно действие.
Получившийся массив должен иметь размер 5x2.

In [73]:
a_centered = a - mean_a
print(a_centered)
a_centered.shape

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


(5, 2)

# Задание 4
Найдите скалярное произведение столбцов массива a_centered.
В результате должна получиться величина a_centered_sp. 
Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [83]:
a_centered_sp = a_centered[:,0] @ a_centered[:,1]
a_centered_sp = a_centered_sp / (a.shape[0] - 1)
print(a_centered_sp)

2.0


# * Задание 5
Число, которое мы получили в конце задания 3 является 
ковариацией двух признаков, содержащихся в массиве а.
В задании 4 мы делили сумму произведений центрированных 
признаков на N-1, а не на N, поэтому полученная нами величина 
является несмещенной оценкой ковариации.
Подробнее узнать о ковариации можно здесь:
Ссылка
В этом задании проверьте получившееся число, вычислив
ковариацию еще одним способом - с помощью функции np.cov.
В качестве аргумента m функция np.cov должна принимать транспонированный массив a.
В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение 
ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.

In [86]:
print(np.cov(a.T))
if np.cov(a.transpose())[0, 1] == a_centered_sp:
    print("Все совпало!")

[[1.  2. ]
 [2.  4.3]]
Все совпало!
